# Generated by Django 4.1.1 on 2022-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0002_alter_credits_return_date_alter_credits_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='credit_id',
            field=models.IntegerField(),
        ),
    ]
