# Generated by Django 4.1.1 on 2022-10-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0003_alter_payments_credit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='return_date',
            field=models.DateField(),
        ),
    ]
