# Generated by Django 4.1.1 on 2022-10-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0007_alter_credits_actual_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='issuance_date',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='return_date',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
    ]
