# Generated by Django 4.1.1 on 2022-10-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0008_alter_credits_issuance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='actual_return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='credits',
            name='issuance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='credits',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='credits',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
