# Generated by Django 4.1.1 on 2022-10-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0009_alter_credits_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='credit_id',
            field=models.IntegerField(),
        ),
    ]
