# Generated by Django 4.1.1 on 2022-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0010_alter_payments_credit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='actual_return_date',
            field=models.DateField(blank=True),
        ),
    ]
