# Generated by Django 4.1.1 on 2022-10-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0011_alter_credits_actual_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='actual_return_date',
            field=models.DateField(null=True),
        ),
    ]
