# Generated by Django 4.1.1 on 2022-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0013_alter_credits_actual_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='type_id',
            field=models.IntegerField(),
        ),
    ]
