# Generated by Django 4.1.1 on 2022-10-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0014_alter_payments_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfsite.users'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='credit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfsite.credits'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfsite.dictionary'),
        ),
    ]
