# Generated by Django 4.1.1 on 2022-10-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0017_rename_user_id_credits_user_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credits',
            old_name='user_id_id',
            new_name='user_id',
        ),
    ]
