# Generated by Django 4.1.1 on 2022-10-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0020_rename_user_id_id_credits_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
